num1 = int(input("Enter your First Number: "))
num2 = int(input("Enter your Second Number: "))
print()
print("Addition=", num1 + num2)
print("Subtraction=", num1 - num2)
print("Multiplication=", num1 * num2)
print("Division=", num1 / num2)
print("Floor Division=", num1 // num2)
print("Remainder=", num1 % num2)
print("Power=", num1 ** num2)